### ISSUE TITLE
Phoebus client references `/usr/bin`

### ISSUE THREAD

**Issue by minijackson** [epics-extensions/EPNix#100]
Opening the `terminal` view in Phoebus on NixOS leads to the error `Cannot run program '/usr/bin/python', No such file or directory`.

It can be changed either at runtime by setting `org.phoebus.applications.console/shell=${pkgs.python3}/bin/python`, or by patching the software at build time.

There's also `/usr/bin/xterm` that's reference in an example view, but I think it should be fine to leave it as-is.

cc @stephane-cea for finding the issue

**Comment by stephane-cea** [comment]
Thanks a lot for proposing a solution so quickly !jjjjjjjjjjjjj
