### ISSUE TITLE
Missing parameter for alarm logger in the documentation

### ISSUE THREAD

**Issue by lcaouen** [epics-extensions/EPNix#53]
The following parameter is missing in the documentation (https://epics-extensions.github.io/EPNix/nixos/guides/phoebus-alarm.html#enabling-the-phoebus-alarm-services) :
```
services.phoebus-alarm-logger.settings."bootstrap.servers" = "${kafkaSock}";
```
This parameter is necessary if kafka is configured to listen to a different ip than localhost
Could you add it ?

**Comment by minijackson** [comment]
Done in #60
